version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "yourStrong#Password"
      MSSQL_USER_NAME: "sa"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    container_name: SQLserver
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
